### PR TITLE
fix boot release tasks to create the jar before attempting to push it

### PR DESCRIPTION
**Pull request by flyingmachine**
Turns out the exception on CI was because `push-release-without-gpg` was expecting to find a jar file in the target directory. Adding the `make` remedies this by building the jar.

### CODE REVIEW

**Comment by christianromney** [comment]
Ah, of course. That's a simple change and fix. I can test it locally.

**Comment by christianromney** [comment]
Just tested locally and that gets us past the previous issue.

**Comment by cldwalker** [comment]
@flyingmachine Good to merge. I'm assuming this wasn't used for release

**Comment by flyingmachine** [comment]
It wasn't; in testing the change I ended up pushing the release

**Comment by christianromney** [comment]
Well it will kick off now. Did we bump the version? :)

**Comment by flyingmachine** [comment]
now we get to see what happens when circle tries to push a release that already exists :-O

**Comment by christianromney** [comment]
Surprised boot ecosystem doesn't already have something like this: https://github.com/relaynetwork/lein-release Well, there's an opportunity...

**Comment by christianromney** [comment]
haha now we know! the build fails.

**Comment by flyingmachine** [comment]
haha yeah :P at least it looks like the credentials for pushing were set up correctly

**Pull request merged**
