### PR TITLE
FIX invalid fspecs in core

### PR DESCRIPTION
**Pull request by stevebuik**
https://github.com/reifyhealth/specmonstah/issues/42

I'm working with a deps.edn project so I can't use my fork with this fix. Could you let me know if you can do another release soon or should I add a deps.edn to my own fork?

Thanks.

### CODE REVIEW

**Comment by stevebuik** [comment]
it was quick to add a deps.edn to my fork so not urgent. 

https://github.com/stevebuik/specmonstah/commit/ab54215e5092eb81ac67ea4b4bee8b0b52067ab6

BTW : thanks for a super-useful lib!

**Comment by cldwalker** [comment]
@stevebuik Thanks for the spec fixes!
@flyingmachine What do you think about adding a deps.edn to the project?

**Comment by flyingmachine** [comment]
@stevebuik thank you so much this! these issues have been fixed with #48 . Thanks again, and sorry for taking so long to get this resolved!

**Comment by stevebuik** [comment]
@flyingmachine no problem, I've been using a forked version so I'll switch back. thanks again

**Comment by stevebuik** [comment]
I tried switching but it's still missing the deps.edn so no good for tools.deps projects. the file in my 2nd commit will fix this.

**Pull request closed without merging**
