### PR TITLE
Make project run in cljs

### PR DESCRIPTION
**Pull request by cldwalker**
@flyingmachine @tomjkidd This PR is an effort to have specmonstah run in cljs. Bumped deps for reasons describe in commits.

Most tests pass in cljs but 3 are failing. I see that `selected-ents` is failing and since other failing tests also use this fn perhaps that's the main source of error? Nothing obvious jumped out in our code as being cljs incompatible so perhaps it's a loom issue. Could use your help when y'all have a chance

### CODE REVIEW

**Comment by flyingmachine** [comment]
I'd love to look at this later today

**Comment by cldwalker** [comment]
> I'd love to look at this later today

Would love to get your 👀  on it. Created https://www.pivotaltracker.com/story/show/149408267 for this

**Comment by flyingmachine** [comment]
I will look at this first thing tomorrow :)

**Comment by flyingmachine** [comment]
if you want we can bump to `1.1.1` and cut a release :)

**Comment by cldwalker** [comment]
@flyingmachine Thanks for the explanation and knocking this out! :fist_right: 🚢  :fist_left: Merge at your leisure

**Pull request merged**
